"""


Consider all integer combinations for a^b for 2 < a < 5 and 2 < b < 5
...

How many distinct terms are in the sequence generated by a^b for 2 < a&b < 100
"""
seq = []
for a in range(2,101,1):
	for b in range(2,101,1):
		calc = a**b
		if calc not in seq: # Instead, only print the distinct values after appended every
			seq.append(calc)
print(len(seq))